FROM --platform=linux/arm64 node:20-slim AS dist
WORKDIR /app
COPY ./package.json ./package.json
COPY ./build.js ./build.js
COPY ./client/ ./client/
COPY ./i18n/ ./i18n/
ARG CONTEXT_PATH
ENV CONTEXT_PATH=$CONTEXT_PATH
RUN npm install
RUN npm run build

FROM --platform=linux/arm64 nginx:latest
COPY ./web/nginx.conf /etc/nginx/nginx.conf
COPY --chown=nginx:nginx ./web/error.html /usr/share/nginx/html/error.html
COPY --chown=nginx:nginx ./web/sorry.html /usr/share/nginx/html/sorry.html
COPY --from=dist --chown=nginx:nginx /app/dist/ /usr/share/nginx/html/
EXPOSE 80